// AUTO-GENERATED by scripts/gen-fields.ts — do not edit
import { FieldRef } from "../fieldRef.js";

export const basicUsageFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  mode: new FieldRef<string>("mode"),
  basicUsageType: new FieldRef<string>("basicUsageType"),
  debitAmount: new FieldRef<number>("debitAmount"),
  metadata: new FieldRef<string>("metadata"),
} as const;

export const aiTokenFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  mode: new FieldRef<string>("mode"),
  model: new FieldRef<string>("model"),
  inputTokens: new FieldRef<number>("inputTokens"),
  outputTokens: new FieldRef<number>("outputTokens"),
  inputDebitAmount: new FieldRef<number>("inputDebitAmount"),
  outputDebitAmount: new FieldRef<number>("outputDebitAmount"),
  provider: new FieldRef<string>("provider"),
  inputCacheTokens: new FieldRef<number>("inputCacheTokens"),
  inputCacheDebitAmount: new FieldRef<number>("inputCacheDebitAmount"),
  metadata: new FieldRef<string>("metadata"),
} as const;

export const paymentFields = {
  eventId: new FieldRef<string>("eventId"),
  eventType: new FieldRef<string>("eventType"),
  userId: new FieldRef<string>("userId"),
  reportedTimestamp: new FieldRef<string>("reportedTimestamp"),
  ingestedTimestamp: new FieldRef<string>("ingestedTimestamp"),
  apiKeyId: new FieldRef<string>("apiKeyId"),
  mode: new FieldRef<string>("mode"),
  creditAmount: new FieldRef<number>("creditAmount"),
} as const;
