// Generated by scrawn tag sync. Do not edit manually.
import { tag as _tag } from "@scrawn/core";
import type { TagExpr } from "@scrawn/core";

export type ScrawnTag = "PREMIUM_CALL" | "EXTRA_FEE";

export function tag(name: ScrawnTag): TagExpr {
  return _tag(name);
}
