// Generated by scrawn tag sync. Do not edit manually.
import { createScrawn } from "@scrawn/core";
import { TAGS } from "./tags";

export const biller = createScrawn({
  apiKey: (process.env.SCRAWN_KEY || process.env.SCRAWN_API_KEY) as string,
  baseURL: (process.env.SCRAWN_BASE_URL || "http://localhost:8070") as string,
  tags: TAGS,
});
