// Generated by scrawn tag sync. Do not edit manually.

export const TAGS = ["PREMIUM_CALL", "EXTRA_FEE"] as const;
export type ScrawnTag = (typeof TAGS)[number];

export const EXPRESSIONS = ["COMPLEX_FEE", "PER_TOKEN_INPUT"] as const;
export type ScrawnExpr = (typeof EXPRESSIONS)[number];
